---
- name: GRAB F5 FACTS
  hosts: all
  connection: local
  gather_facts: no

  tasks:

    - name: COLLECT BIG-IP FACTS
      bigip_device_info:
        gather_subset:
          - system-info
        provider:
          server: "{{server}}"
          user: "{{ansible_user}}"
          server_port: 443
          validate_certs: no
      register: device_facts

    - name: DISPLAY COMPLETE BIG-IP SYSTEM INFORMATION
      debug:
        var: device_facts


