---
- name: GRAB F5 FACTS
  hosts: all
  connection: local
  gather_facts: no

  tasks:

    - name: COLLECT BIG-IP FACTS
      bigip_device_info:
        gather_subset:
          - all
        provider:
          server: 192.168.20.231
          user: "{{ansible_user}}"
          server_port: 443
          validate_certs: no
      register: device_facts

    - name: DISPLAY COMPLETE BIG-IP SYSTEM INFORMATION
      debug:
        var: device_facts

    - name: DISPLAY ONLY THE MAC ADDRESS
      debug:
        var: device_facts['system_info']['base_mac_address']

    - name: DISPLAY ONLY THE VERSION
      debug:
        var: device_facts['system_info']['product_version']

    - name: DISPLAY WIDE IP
      debug:
        var: device_facts['gtm_wide_ips']['pool_lb_mode']

