---
- name: Create a VIP, pool and pool members
  hosts: all
  connection: local

  vars:
    provider:
        password: admin
        server: 1.1.1.1
        user: admin
        validate_certs: no
        server_port: 443

  tasks:
  
  - name: Create a pool
    bigip_pool:
     provider: "{{ provider }}"
     lb_method: ratio-member
     name: web
     slow_ramp_time: 120
    delegate_to: localhost

