---
- name: LTM node ntt
  hosts: all
  connection: local
  gather_facts: no

  tasks:

    - name: Enabled or disable pool member pjdc - ntt dwdm
      bigip_pool_member:
        state: "{{state_1}}"
        name: "pjdc_2"
        pool: "second_dwdm"
        port: "80"
        address: "10.10.10.106"
        provider:
          server: 192.168.20.232
          user: "{{ansible_user}}"
          server_port: 443
          validate_certs: no
      delegate_to: localhost

    - name: Enabled or disable pool member cinderella - ntt dwdm
      bigip_pool_member:
        state: "{{state_2}}"
        name: "cinderella_2"
        pool: "second_dwdm"
        port: "80"
        address: "10.10.10.107"
        provider:
          server: 192.168.20.232
          user: "{{ansible_user}}"
          server_port: 443
          validate_certs: no
      delegate_to: localhost

    - name: Enabled or disable pool member ntt - ntt dwdm
      bigip_pool_member:
        state: "{{state_3}}"
        name: "ntt_2"
        pool: "second_dwdm"
        port: "80"
        address: "10.10.10.108"
        provider:
          server: 192.168.20.232
          user: "{{ansible_user}}"
          server_port: 443
          validate_certs: no
      delegate_to: localhost

