---
- name: LTM node pjdc
  hosts: all
  connection: local
  gather_facts: no

  tasks:

    - name: Enabled or disable pool member pjdc - pjdc dwdm
      bigip_pool_member:
        state: "{{state_1}}"
        name: "pjdc_dwdm"
        pool: "web"
        port: "80"
        address: "10.10.10.100"
        provider:
          server: 192.168.20.231
          user: "{{ansible_user}}"
          server_port: 443
          validate_certs: no
      delegate_to: localhost

    - name: Enabled or disable pool member cinderella - pjdc dwdm
      bigip_pool_member:
        state: "{{state_2}}"
        name: "cinderella_dwdm"
        pool: "web"
        port: "80"
        address: "10.10.10.101"
        provider:
          server: 192.168.20.231
          user: "{{ansible_user}}"
          server_port: 443
          validate_certs: no
      delegate_to: localhost

    - name: Enabled or disable pool member ntt - pjdc dwdm
      bigip_pool_member:
        state: "{{state_3}}"
        name: "ntt_dwdm"
        pool: "web"
        port: "80"
        address: "10.10.10.102"
        provider:
          server: 192.168.20.231
          user: "{{ansible_user}}"
          server_port: 443
          validate_certs: no
      delegate_to: localhost

